#Comentario añadido por Álvaro
#¡Holi! Te añado un chiste malo:
# - ¡Jesús! ¿Qué tal la última cena? ¿Salió cara?
# - No... Salió cruz.



# -*- coding: utf-8 -*-
"""ANKARA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1swagHM5VRnxs3oBrVY8_Llb0_PR5wLi9
"""

### RED SOCIAL: CUADERNO 7 - LARA MAESO ASUMU

## IMPORTADOS
import os # Importamos el sistema operativo para encontrar archivos
import re # Expresiones regulares

## DATOS
# Diccionario de provincias españolas por comunidad autónoma
provincias = {
    "Andalucía": [
        "almería",
        "cádiz",
        "córdoba",
        "granada",
        "huelva",
        "jaén",
        "málaga",
        "sevilla"
    ],
    "Aragón": [
        "huesca",
        "zaragoza",
        "teruel"
    ],
    "Asturias": ["asturias"],
    "Cantabria": ["cantabria"],
    "Castilla-La Mancha": [
        "albacete",
        "ciudad real",
        "cuenca",
        "guadalajara",
        "toledo"
    ],
    "Castilla y León": [
        "ávila",
        "burgos",
        "león",
        "palencia",
        "salamanca",
        "segovia",
        "soria",
        "valladolid",
        "zamora"
    ],
    "Cataluña": [
        "barcelona",
        "girona",
        "lleida",
        "tarragona"],
    "Comunidad de Madrid": ["madrid"],
    "Comunidad Valenciana": [
        "alicante",
        "castellón",
        "valencia"
    ],
    "Extremadura": [
        "badajoz",
        "cáceres"
    ],
    "Galicia": [
        "a coruña",
        "lugo",
        "ourense",
        "pontevedra"
    ],
    "Islas Baleares": ["islas baleares"],
    "Islas Canarias": [
        "santa cruz de tenerife",
        "las palmas"
    ],
    "La Rioja": ["la rioja"],
    "Navarra": ["navarra"],
    "País Vasco": [
        "álava",
        "guipúzcoa",
        "vizcaya"
    ],
    "Región de Murcia": ["murcia"]
}


## FUNCIONES

def preguntar_opcion(): # Imprime el menú y devuelve la opción elegida por el usuario
    print("MENÚ")
    print()
    print("1. Rellenar mi perfil de usuario")
    print("2. Modificar mis datos")
    print("3. Ver mi perfil")
    print("4. Publicar un mensaje de estado")
    print("5. Salir")
    print()

    return int(input("Elige tu opción: "))


def pedir_datos(): # Pide datos al usuario

  nombre = input("¿Cuál es tu nombre?: ").capitalize()
  apellidos = input("¿Cuáles son tus apellidos? ").capitalize()
  correo = input("¿Cuál es tu correo electrónico?").lower()
  while not re.match(r"^[\w.-]+@[\w.-]+\.[A-Za-z]{2,}$", correo): # Limitamos la respuesta del usuario a un formato de correo concreto.
    correo = input("Introduce un correo con el formato adecuado: ")

  # Edad del usuario
  fecha = input("¿Cuál es tu fecha de nacimiento (dd/mm/aaaa): ")
  while not re.match(r"^\d{2}/\d{2}/\d{4}$", fecha): # Limitamos con regex el formato de la fecha y volvemos a preguntar.
    fecha = input("Introduce la fecha con el formato (dd/mm/aaaa): ")

  dia_nacimiento = int(fecha[0:2]) # Hacemos slicing para guardar cada parte en una variable
  mes_nacimiento = int(fecha[3:5])
  año_nacimiento = int(fecha[6:10])
  año_actual = 2025
  mes_actual = 10
  dia_actual = 25
  # Le felicitamos si es el día de su cumpleaños
  if mes_nacimiento == mes_actual and dia_nacimiento == dia_actual:
      print("¡Feliz cumpleaños! :)")
      print()

  if mes_nacimiento > mes_actual or mes_nacimiento == mes_actual and dia_nacimiento > dia_actual:
      edad = año_actual - año_nacimiento -1
  else:
      edad = año_actual - año_nacimiento

  # Continua el cuestionario
  ankara = input("¿De qué país provienen tus raíces? ").capitalize()
  cultura = input("¿De qué etnia o grupo cultural? ").capitalize()
  altura = float(input("¿Cuál es tu estatura (en centímetros)? "))/100

  # Pregutamos por la provincia al usuario para rellenar con otras fuentes
  provincia = input("¿En qué provincia española vives?: ")

  for comunidad in provincias: # Recorremos comunidades (claves) y provincias (dentro de las listas)

      lista_provincias = provincias[comunidad] # Accedemos a las listas

      if provincia.lower() in lista_provincias:
          vive_en = f"{provincia.capitalize()}, {comunidad.capitalize()}"

  # Info que sirve a otros usuarios para identificar necesidades o intereses compartidos
  print()
  proposito = input("¿Qué te ha traído a Ankara y qué te gustaría recibir de tu comunidad? ")

  return (nombre, apellidos, correo, edad, ankara, cultura, altura, vive_en, proposito)


def imprimir_perfil(perfil): # Imprime el perfil del usuario
  nombre, apellidos, correo, edad, ankara, cultura, altura, vive_en, proposito = perfil
  print()
  print("Nombre:", nombre)
  print("Apellidos:", apellidos)
  print("Correo electrónico:", correo)
  print("Edad:", edad)
  print("Ankara:", ankara, ",", cultura)
  print("Altura: ", altura, "m")
  print()
  print("Localización: ", vive_en) # Provincia y comunidad autónoma ya sacada del conjunto
  print()
  print("Propósito: ", proposito)
  print()

def guardar_datos(perfil): # Recibe los datos de pedir_datos() y los guarda en un fichero ya procesados
  nombre, apellidos, correo, edad, ankara, cultura, altura, vive_en, proposito = perfil
  with open(f"{nombre}.user", "w", encoding = "UTF-8") as fichero:
    fichero.write(nombre + "\n" + apellidos + "\n" + correo + "\n" + str(edad) + "\n" + ankara + "\n" + cultura + "\n" + str(altura) + "\n" + vive_en + "\n" + proposito + "\n")


def crear_perfil(): # Crea el perfil con los datos almacenados y lo imprime
  ruta = input("¿Cuál es tu nombre?: ").capitalize()
  if not os.path.isfile(f"{ruta}.user"):
    perfil = pedir_datos()
    guardar_datos(perfil)
    print()
    print("Tu perfil ha sido creado: ")
    print()
    imprimir_perfil(perfil)
    return perfil
  else:
    print()
    print("Ya existe un perfil con ese nombre")
    print()
    return None

def consultar_perfil(): # Consulta si existe el fichero correspondiente a este usuario y lo imprime
  ruta = input("¿Cuál es tu nombre?: ")
  if os.path.isfile(f"{ruta}.user"):
    with open(f"{ruta}.user", "r", encoding = "UTF-8") as fichero:
      lineas = fichero.readlines()
      if len(lineas) > 7:
        for linea in lineas[:7]:
          print(linea.strip())
        print("Mensajes")
        for linea in lineas[7:]:
          print(linea.strip())
      else:
        for linea in lineas:
          print(linea.strip())   
  else:
    print()
    print("No existe ningún perfil con ese nombre")
    print()
        

def modificar_perfil(): # Modifica el perfil ya creado e imprime los datos actualizados
  ruta = input("¿Cuál es tu nombre?: ")
  if os.path.isfile(f"{ruta}.user"):
    perfil_actualizado = pedir_datos()
    guardar_datos(perfil_actualizado)
    print()
    print("Tu perfil ha sido modificado")
    print()
    imprimir_perfil(perfil_actualizado)
  else:
    print()
    print("No existe ningún perfil con ese nombre")
    print()
    
  return perfil_actualizado

def publicar_mensaje(): # Publica un estado con el input del usuario
  ruta = input("¿Cuál es tu nombre?: ")
  if os.path.isfile(f"{ruta}.user"):
    print()
    with open(f"{ruta}.user", "a", encoding = "UTF-8") as fichero:
      mensaje = input("¿En qué estás pensando? ")
      print()
      fichero.write(f"{ruta} ha publicado:\n{mensaje}\n")


## PROGRAMA

#Ankara es una red social en la que las personas de cualquier diáspora migratoria pueden reencontrarse con su memoria cultural, intercambiando experiencias, conocimientos y aspectos culturales de su etnia de origen. Los usuarios pueden, además, establecer nuevos vínculos con personas de su etnia como red de apoyo y recuperar o redefinir aspectos culturales en peligro de conservación, bajo consideración popular.
#Ankara significa tierra, suelo, orígen, en bubi.
print()
print()
print()
print(r"       ><       ><<<     ><<><<   ><<        ><       ><<<<<<<          ><        ")
print(r"      >< <<     >< ><<   ><<><<  ><<        >< <<     ><<    ><<       >< <<      ")
print(r"     ><  ><<    ><< ><<  ><<><< ><<        ><  ><<    ><<    ><<      ><  ><<     ")
print(r"    ><<   ><<   ><<  ><< ><<>< ><         ><<   ><<   >< ><<         ><<   ><<    ")
print(r"   ><<<<<< ><<  ><<   >< ><<><<  ><<     ><<<<<< ><<  ><<  ><<      ><<<<<< ><<   ")
print(r"  ><<       ><< ><<    >< <<><<   ><<   ><<       ><< ><<    ><<   ><<       ><<  ")
print(r" ><<         ><<><<      ><<><<     ><<><<         ><<><<      ><<><<         ><< ")
print()
print(r"         T U         R A Í Z          E N         L A           R E D                        ")
print()
print()
print()

#Menú de navegación con bucle
continuar = True
perfil_creado = False

while continuar:
  opcion = int(preguntar_opcion())

  #Rutas posibles en el menú

  if opcion == 1:
    crear_perfil()

  elif opcion == 2:
    modificar_perfil()

  elif opcion == 3:
    consultar_perfil()
  
  elif opcion == 4:
    publicar_mensaje()

  elif opcion == 5:
    # Paramos el bucle para salir del programa
    print()
    print("Gracias por acercarte a tu raíz con Ankara :)")
    print("¡Hasta pronto!")
    print()
    continuar = False

  else:
    # Si el usuario escribe otra cosa fuera del rango, le reconducimos
    print("Tienes que escoger un número del 1 al 4")